### ISSUE TITLE
Дрогобич, правки

### ISSUE THREAD

**Issue by drohobych-city** [OPORA/publicwhip-drohobych#1]
1. "Про проект" правлений текст (надіслав на пошту Юрію)
2. Коли заходиш на рішення пише "Голосування Львівської міської ради", а має бути Дрогобицької
3. Коли заходиш на рішення не працюють кнопки "Текст рішення", "CSV", "PNG", "Поширити"
4. Коли заходиш на депутати то в  пошуку випадає знизу "Андрій Садовий"
5. Коли заходиш на сумісні голосування то останні показують чорним а заголовок пише  "Сумісні голосування позапартійний"

**Comment by beastie87** [comment]
2) Коли заходиш на рішення пише "Голосування Львівської міської ради", а має бути Дрогобицької - виправив

**Comment by beastie87** [comment]
створюйте будь ласка на кожну багу чи питання нове issues

**Comment by beastie87** [comment]
4 Коли заходиш на депутати то в пошуку випадає знизу "Андрій Садовий" - зробіть будь ласка прінскрін, як я розумію попередньо це кеш Львівської міськ ради в Вашоиу браузері

**Comment by beastie87** [comment]
5 Коли заходиш на сумісні голосування то останні показують чорним а заголовок пише "Сумісні голосування позапартійний" - зазвичай хватає 7 кольрів для побудови графіку тому тут ще 2 мають чорний колір так як ми не вказали 9 різних кольрів а тільки 7, стосовно позапартійний - то в датасеті депутатів - "faction":"Позапартійний" - то от того там так пише )

**Comment by beastie87** [comment]
"Текст рішення" - є десь посилання чи вставленний текст в датасетах? Вибачте може я десь пропустив де є така інформація?

**Comment by beastie87** [comment]
"CSV" - яку б форму файлу Ви б хотіли бачити?
"PNG", - яку картинку генерувати з якої частитини сторінки
 "Поширити" - куди саме і що саме поширювати?

**Comment by lisoffsky** [comment]
@drohobych-city 
1,2 правимо, 3 зробимо трохи пізніше. 
4. ви маєте на увазі [ось це посилання](https://drohobych.rada4you.org/people)? Там Садового немає, є Андрухів.
![image](https://user-images.githubusercontent.com/14181306/35228495-8dd069f6-ff99-11e7-91b5-a13c8503e944.png)

5. виправимо на ПОЗАФРАКЦІЙНІ. @beastie87

**Comment by lisoffsky** [comment]
@beastie87 це просто недоверстано, якщо я правильно розумію https://github.com/OPORA/publicwhip-drohobych/issues/1#issuecomment-359455834

**Comment by beastie87** [comment]
@drohobych-city @lisoffsky  1 та 2 поправив, перевіряйте будь ласка
