### ISSUE TITLE
Сторінка створення політики

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-drohobych#17]
[ось ця сторінка](https://drohobych.rada4you.org/policies/new)

в акордеоні "Корисні поради..."
![image](https://user-images.githubusercontent.com/14181306/42757100-5f9464dc-8907-11e8-856e-341a88e99052.png)

замінити "законопроекти" на "голосування"
"парламентом" на "міською радою"

**Comment by beastie87** [comment]
Fix done! I closed this, but If you have questions, please reopen this issues
