### ISSUE TITLE
Додати пояснення для ліцензування CC4 на сторінці створення політики

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-drohobych#18]
[на цій сторінці](https://drohobych.rada4you.org/policies/new)

додати ось такий "акордеон" внизу
![image](https://user-images.githubusercontent.com/14181306/42757230-e5d7322c-8907-11e8-9d9d-c48260bae2ca.png)

**Comment by beastie87** [comment]
I added text about license and close this issues
You will reopen if you need any answer about that topic
