### ISSUE TITLE
активні лінки в історії редагувань політик. Мій кабінет

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-drohobych#19]
[Зробити в історії редагувань](https://drohobych.rada4you.org/auth/register/edit)

назви політик посиланнями на ці політики

назву голосування лінком на це голосування

ось як зараз
![image](https://user-images.githubusercontent.com/14181306/43387016-f8fb6ed6-93ed-11e8-8197-e0fb65ddc3ae.png)

і ось як потрібно (як на rada4you.org)
![image](https://user-images.githubusercontent.com/14181306/43387048-124a47fe-93ee-11e8-813e-7b8bdaa245bc.png)

**Comment by beastie87** [comment]
готово
