### ISSUE TITLE
перекласти англійський текст у прив'язування голосування до політики

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-drohobych#20]
Коли прив'язував голосування до політики, забув додати політику, але натис Зберегти. 
вийшла помилка. 

![image](https://user-images.githubusercontent.com/14181306/43387556-6a3515c4-93ef-11e8-87a0-9c18245f8799.png)

треба [ось тут](https://drohobych.rada4you.org/policy_divisions) замінити текст

"1 error prohibited this policy_division from being saved:"
на
"помилка при додаванні голосування до політики"

і текст 
"Policy must exist"
на 
"Необхідно обрати політику"

**Comment by beastie87** [comment]
не тут, треба переробити логіку....

**Comment by beastie87** [comment]
Готово
