### ISSUE TITLE
Інтекративні лінки в історії змін конкретної політики

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-drohobych#21]
наприклад [у цій політиці](https://drohobych.rada4you.org/policies/2?history=1) варто зробити інтерактивними 

- назву голосування
- логін користувача -> на всі редагування користувача

приклад [тут](https://rada4you.org/policies/121/history)  
![image](https://user-images.githubusercontent.com/14181306/43387886-5792866c-93f0-11e8-8314-1321365849e7.png)

пов'язане issue #19

**Comment by beastie87** [comment]
я незнаю як оформити публічну сторінку всіх історій редагувань конкретного користувача, в прототипі вона приватна і так вона й працює

**Comment by beastie87** [comment]
Готова
