### ISSUE TITLE
пошук за фракційною дисципліною та присутністю збільшити від 0 до 100

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-drohobych#26]
При пошуку голосувань за фракційною дисципліною та присутністю по замовчуванню встановлено від 30 до 90. чи можна збільшити діапазон від 0 до 100?

ось так зараз 
![image](https://user-images.githubusercontent.com/14181306/48203622-af330980-e370-11e8-881d-2e07486bbc93.png)

**Comment by beastie87** [comment]
ще одна бага при пошуці після всих правок відкривається фільтрація по даті і за остані місяці може не бути результату

**Comment by beastie87** [comment]
Готово, перевіряйте будь ласка
