### ISSUE TITLE
зауваження по верстці

### ISSUE THREAD

**Issue by GS-0001** [OPORA/publicwhip-drohobych#7]
на сторінці депутатів картка депутата просто "влипає" у футер.

**чи нема можливості для таких сторінок зробити якийсь проміжок/простір перед футером?**

![2018-03-20_11_29_25](https://user-images.githubusercontent.com/15831533/37891981-f6007536-30de-11e8-8d4f-e5f6b8a682b3.png)

**Comment by beastie87** [comment]
@GS-0001 ти не повіриш але можливо ось
![image](https://user-images.githubusercontent.com/14181304/42835756-4072dbf0-8a02-11e8-9180-d2de9e41fd3b.png)
я закриваю це питання, якщо знайдете проблему то можете перевідкрити. Дякую
