### ISSUE TITLE
В описі замінити Львів на Дрогобич

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-drohobych#8]
ось тут Львівською замінити на Дрогобицькою
![image](https://user-images.githubusercontent.com/14181306/37895601-7856109e-30ea-11e8-8e95-b63e153e5c09.png)

а тут львів'ян замінити на дрогобичан
![image](https://user-images.githubusercontent.com/14181306/37895630-8e424c38-30ea-11e8-8ec6-d4d7a4574b93.png)

**Comment by beastie87** [comment]
@lisoffsky виправлено :smiley_cat:
